'use client';
import { useCallback } from 'react';

interface SessionReportData {
  sessionId: string;
  startTime: number;
  endTime: number;
  mode: 'PERPS' | 'INVEST';
  trades: Array<{
    timestamp: number;
    action: string;
    asset: string;
    amount: number;
    pnl: number;
    reasoning?: string;
  }>;
  totalPnL: number;
  totalPnLPercent: number;
  budget: number;
  walletAddress: string;
  llmProvider?: string;
  oodaCycles: number;
}

export function useSessionReport() {
  const generateReport = useCallback((data: SessionReportData): string => {
    const startDate = new Date(data.startTime).toISOString();
    const endDate = new Date(data.endTime).toISOString();
    const duration = Math.round((data.endTime - data.startTime) / 60000);
    const winCount = data.trades.filter(t => t.pnl > 0).length;
    const lossCount = data.trades.filter(t => t.pnl < 0).length;
    const winRate = data.trades.length > 0 ? ((winCount / data.trades.length) * 100).toFixed(1) : '0';

    let report = `# Makora Session Report\n\n`;
    report += `> Generated by Makora — LLM-Powered DeFi Agent on Solana\n\n`;
    report += `---\n\n`;
    report += `## Session Overview\n\n`;
    report += `| Field | Value |\n|-------|-------|\n`;
    report += `| Session ID | \`${data.sessionId}\` |\n`;
    report += `| Mode | **${data.mode}** |\n`;
    report += `| Start | ${startDate} |\n`;
    report += `| End | ${endDate} |\n`;
    report += `| Duration | ${duration} minutes |\n`;
    report += `| Wallet | \`${data.walletAddress}\` |\n`;
    report += `| LLM Provider | ${data.llmProvider || 'N/A'} |\n`;
    report += `| OODA Cycles | ${data.oodaCycles} |\n`;
    report += `| Budget | ${data.budget} SOL |\n\n`;

    report += `## Performance Summary\n\n`;
    report += `| Metric | Value |\n|--------|-------|\n`;
    report += `| Total P&L | **${data.totalPnL >= 0 ? '+' : ''}${data.totalPnL.toFixed(4)} SOL** (${data.totalPnLPercent >= 0 ? '+' : ''}${data.totalPnLPercent.toFixed(2)}%) |\n`;
    report += `| Total Trades | ${data.trades.length} |\n`;
    report += `| Wins / Losses | ${winCount} / ${lossCount} |\n`;
    report += `| Win Rate | ${winRate}% |\n`;

    if (data.trades.length > 0) {
      const bestTrade = data.trades.reduce((a, b) => a.pnl > b.pnl ? a : b);
      const worstTrade = data.trades.reduce((a, b) => a.pnl < b.pnl ? a : b);
      report += `| Best Trade | +${bestTrade.pnl.toFixed(4)} SOL (${bestTrade.action} ${bestTrade.asset}) |\n`;
      report += `| Worst Trade | ${worstTrade.pnl.toFixed(4)} SOL (${worstTrade.action} ${worstTrade.asset}) |\n`;
    }

    report += `\n## Trade Log\n\n`;
    report += `| # | Time | Action | Asset | Amount | P&L | Reasoning |\n`;
    report += `|---|------|--------|-------|--------|-----|----------|\n`;

    data.trades.forEach((trade, i) => {
      const time = new Date(trade.timestamp).toLocaleTimeString();
      const pnlStr = trade.pnl >= 0 ? `+${trade.pnl.toFixed(4)}` : trade.pnl.toFixed(4);
      const reason = trade.reasoning ? trade.reasoning.slice(0, 60) + (trade.reasoning.length > 60 ? '...' : '') : '-';
      report += `| ${i + 1} | ${time} | ${trade.action} | ${trade.asset} | ${trade.amount.toFixed(4)} | ${pnlStr} | ${reason} |\n`;
    });

    report += `\n---\n\n`;
    report += `*Report generated by [Makora](https://github.com/IsSlashy/Makora) — Built by AI (Claude) for the Solana Agent Hackathon*\n`;

    return report;
  }, []);

  const downloadReport = useCallback((data: SessionReportData) => {
    const report = generateReport(data);
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `makora-session-${data.sessionId}-${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [generateReport]);

  return { generateReport, downloadReport };
}
